services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        container_name: laravel
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        command: ["bash", "./startup.sh"]
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_list
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    mysql_testing:
        image: mysql:8.0
        container_name: db_desting
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_list
        volumes:
            - dbdata_testing:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    dbdata:
    dbdata_testing:

networks:
    laravel:
        driver: bridge
